# Generated by Django 5.2.11 on 2026-02-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='author',
        ),
    ]
